# Generated by Django 5.2.5 on 2025-11-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_percentage',
            field=models.IntegerField(default=0, help_text='Task completion percentage (0-100)'),
        ),
    ]
